src/DM.WR.Web/Reskin/Controllers/BackDoorController.cs
using DM.WR.BL.Providers;
using DM.WR.Models.Config;
using DM.WR.Models.ViewModels;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DM.WR.Web.Reskin.Controllers
{
    public partial class BackDoorController : Controller
    {
        private readonly IGlobalProvider _provider;

        public BackDoorController(IGlobalProvider provider)
        {
            _provider = provider;
        }

        [HttpGet]
        public virtual ActionResult Index()
        {
            if (Request.Url != null)
            {
                var host = Request.Url.Host;

                if (host.StartsWith("iowaflexdemo.") && host.Count(h => h == '.') > 1)
                    return RedirectToAction(MVC.Demo.ActionNames.IowaFlex, MVC.Demo.Name);
            }

            var model = _provider.BuildBackDoorModel();
            return View(MVC.BackDoor.Views.ViewNames.BackDoor, model);
        }

        [HttpPost]
        public virtual async Task<ActionResult> Index(EntranceViewModel model)
        {
            model = await _provider.ProcessBackdoorSiteEntry(model);

            if (!string.IsNullOrEmpty(model.ErrorMessage))
                return View(MVC.BackDoor.Views.ViewNames.BackDoor, model);

            if (model.View == WebReportingView.Classic)
                return RedirectToAction(MVC.Options.ActionNames.Index, MVC.Options.Name);
            if (model.View == WebReportingView.IowaFlex)
                return RedirectToAction(MVC.DashboardIowaFlex.ActionNames.Index, MVC.DashboardIowaFlex.Name);
            if (model.View == WebReportingView.Cogat)
                return RedirectToAction(MVC.DashboardCogat.ActionNames.Index, MVC.DashboardCogat.Name);

            return RedirectToAction(MVC.Error.ActionNames.NotFound, MVC.Error.Name);
        }

        public virtual async Task<ActionResult> GetElevate(string token)
        {
            
            var view = WebReportingView.Cogat;

            if (view == null)
                return RedirectToAction(MVC.Error.ActionNames.NotFound, MVC.Error.Name);

            var model = await _provider.ProcessDmSiteEntryElevates(token);

            if (!string.IsNullOrEmpty(model.RedirectToUrl))
                return Redirect(model.RedirectToUrl);
            if (view == WebReportingView.Cogat)
                return RedirectToAction(MVC.DashboardCogat.ActionNames.Index, MVC.DashboardCogat.Name);

            return RedirectToAction(MVC.Error.ActionNames.NotFound, MVC.Error.Name);
        }

        [HttpGet]
        public virtual async Task<ActionResult> GetElevateWithCookie()
        {
            //this endpoint requires the Elevate auth cookies

            var view = WebReportingView.Cogat;
            var cookies = Request.Cookies;
            var idTokenCookie = cookies.Get("idToken");

            if (view == null)
                return RedirectToAction(MVC.Error.ActionNames.NotFound, MVC.Error.Name);

            var model = await _provider.ProcessDmSiteEntryElevate(Request.Cookies);

            if (string.Equals(model.ErrorMessage,"Unauthorized",System.StringComparison.OrdinalIgnoreCase))
            {
                return Redirect(ConfigSettings.ReturnUrl);
            }

            if (!string.IsNullOrEmpty(model.RedirectToUrl))
                return Redirect(model.RedirectToUrl);

            if (!string.IsNullOrEmpty(model.ErrorMessage))
                return RedirectToAction(MVC.Error.ActionNames.NotFound, MVC.Error.Name);

            if (view == WebReportingView.Cogat)
                return RedirectToAction(MVC.DashboardCogat.ActionNames.Index, MVC.DashboardCogat.Name);

            return RedirectToAction(MVC.Error.ActionNames.NotFound, MVC.Error.Name);
        }

        [HttpGet]
        public virtual async Task<ActionResult> AfterRedirection()
        {
            var models = await _provider.ProcessReEntry(Request.Cookies);

            //var model = await _provider.ProcessDmSiteEntryElevate(Request.Cookies);
            return RedirectToAction(MVC.DashboardCogat.ActionNames.Index, MVC.DashboardCogat.Name);
        }
    }
}

src/DM.WR.Web/Reskin/Views/BackDoor/BackDoor.cshtml
@using DM.WR.Models.Config
@model EntranceViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" type="image/png" href="@Links.Reskin.Content.dm_ui.img.dm_fav_png">
    <title>Web Reporting</title>
    @Styles.Render(DmUiBundlePath.CssBundle)
    @Styles.Render(BundlePath.CssBackdoorPage)
    @Scripts.Render(DmUiBundlePath.JsBundle)
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" type="text/css">
</head>
<body style="background-image: url(@Links.Reskin.Content.img.BackDoorBackground_png)">
    <div id="root"></div>
    @Scripts.Render("~/Reskin/Scripts/elevate-external-header/eeh/build/static/main.826aa607.js")

    <div class="body-content">
        <h1>Welcome to Web Reporting!</h1>
        @using (Html.BeginForm("Index", "BackDoor", FormMethod.Post, new { @class = "back-door-form" }))
        {
        @Html.LabelFor(m => m.View)
        @Html.DmUiSingleSelectDropdown(items: Model.ViewList, id: "View")
        <br />
        <div class="classic-login" @Html.Attr(Model.ViewList.Any(i => i.Value == WebReportingView.IowaFlex && i.Selected), "style", "display: none;")>
            @Html.LabelFor(m => m.LocationGuids)
            @Html.TextBoxFor(m=> m.LocationGuids)

            @Html.LabelFor(m => m.ContractInstances)
            @Html.TextBoxFor(m => m.ContractInstances)

            @Html.LabelFor(m => m.RoleName)
            @Html.TextBoxFor(m => m.RoleName)
        </div>

        <div class="adaptive-login" @Html.Attr(Model.ViewList.Any(i => i.Value == WebReportingView.IowaFlex && !i.Selected), "style", "display: none;")>
            @Html.LabelFor(m => m.UserId)
            @Html.TextAreaFor(m => m.UserId)

            @Html.LabelFor(m => m.LocationIds)
            @Html.TextAreaFor(m => m.LocationIds)

            @Html.LabelFor(m => m.LocationLevel)
            @Html.TextAreaFor(m => m.LocationLevel)
        </div>

        <div class="bd-button-container">
            <input id="submit-button" type="submit" class="dm-ui-button-medium dm-ui-button-primary" value="Submit" />
        </div>

        <div class="dm-ui-error-text">@Model.ErrorMessage</div>
        }
    </div>
    @Scripts.Render(DmUiBundlePath.JsBundle)
    <script type="text/javascript">
        $(document).ready(function () {

            DmUiLibrary.Init('settings');

            $('textarea').on('enterkeyup', function () {
                $('form').submit();
            });

            $('#View').on('change', function () {
                if (this.value == 'dashboard_iowaflex') {
                    $('.classic-login').hide();
                    $('.adaptive-login').show();
                }
                else {
                    $('.classic-login').show();
                    $('.adaptive-login').hide();
                }

            });
        });
    </script>
</body>
</html>